import { chromium } from "@playwright/test";
const S = process.argv[2];
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("http://localhost:3100/", { waitUntil: "networkidle" });
await p.waitForTimeout(3000);
await p.screenshot({ path: `${S}/v-hero.png` });
await p.evaluate(async () => { for (let y = 0; y < document.body.scrollHeight; y += 400) { window.scrollTo(0, y); await new Promise(r => setTimeout(r, 100)); } window.scrollTo(0, 0); });
await p.waitForTimeout(2000);
await p.screenshot({ path: `${S}/v-full.png`, fullPage: true });
await b.close();
